//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _19final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class about1
    {
        public int ID { get; set; }
        public string etrafli { get; set; }
    }
}
